/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "pybhmnlimcjrupttaafs"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5YmhtbmxpbWNqcnVwdHRhYWZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg2Mjc5NDYsImV4cCI6MjA4NDIwMzk0Nn0.-sOSa7vkviI7v0f0egGO5cpLSPQ1CBnY8BdDuFY6-LE"